### ISSUE TITLE
MAPA MENTAL BY LÓPEZ DOMÍNGUEZ 

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/actividad-4-mapa-mental-23620031#2]
[mapa_mental_mate.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-23620031/files/12676165/mapa_mental_mate.pdf)

**Comment by Felix-Angel** [comment]
Manejo conceptual: 25%
Relación entre los conjuntos: 25%
Calidad de la presentación: 22% (Falta de colores)
Jerarquía: 25%
Total 19.4/20
Evaluó equipo de Diego, Daniel, Félix Y Mayra.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..de bv...
